/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.agrocomercial.clientes.views.orders;

import com.agrocomercial.clientes.context.AppContext;
import com.agrocomercial.clientes.controller.AddProductToOrderController;
import com.agrocomercial.clientes.events.OrderProductEventListener;
import com.agrocomercial.clientes.models.Product;
import com.agrocomercial.clientes.utils.WindowUtils;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jesus
 */
public class CreateOrderView extends javax.swing.JFrame implements OrderProductEventListener {
    @Override
    public void onProductAdded(Product product, Integer quantity, Double subtotal) {
        DefaultTableModel defaultTableModel = (DefaultTableModel) productTable.getModel();

        defaultTableModel.addRow(new Object[]{product.getName(), quantity, subtotal});
    }

    private final transient AppContext localAppContext;
    private final transient AddProductToOrderController controller;

    public CreateOrderView(AppContext appContext, AddProductToOrderController controller) {
        initComponents();
        this.controller = controller;
        this.localAppContext = appContext;
        subscribeToOrderProductEvent();
    }

    private void subscribeToOrderProductEvent(){
        controller.subscribe(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        orderNumberField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        addProductButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero de orden");

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productTable);

        addProductButton.setText("añadir producto");
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Guardar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addProductButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveButton)
                                .addGap(23, 23, 23)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(orderNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addProductButton)
                    .addComponent(saveButton))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {
        WindowUtils.closeAndShowPanel(this, localAppContext.getAddProductToOrderView());
    }

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {

        String orderNumberStr = orderNumberField.getText();
        long orderNumber;

        try{
            orderNumber = Long.parseLong(orderNumberStr);
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "El número de orden debe ser un número válido.");
            return;
        }

        if (orderNumber <= 0) {
            JOptionPane.showMessageDialog(null, "El número de orden debe ser mayor que cero.");
            return;
        }

        int rows = getProductsTableModel().getRowCount();

        if(rows == 0){
            JOptionPane.showMessageDialog(null, "No se puede crear una orden sin productos");
            return;
        }

        controller.saveOrder(orderNumber);
        JOptionPane.showMessageDialog(null, "Orden creada correctamente");
        clearFields();
    }

    private void clearFields(){
        orderNumberField.setText("");
        DefaultTableModel defaultTableModel = getProductsTableModel();
        int rowCount = defaultTableModel.getRowCount();
        for(int i = 0; i < rowCount; i++){
            defaultTableModel.removeRow(i);
        }
    }

    private DefaultTableModel getProductsTableModel(){
        return (DefaultTableModel) productTable.getModel();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField orderNumberField;
    private javax.swing.JTable productTable;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
