/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.agrocomercial.clientes.views.orders;

import com.agrocomercial.clientes.context.AppContext;
import com.agrocomercial.clientes.controller.OrderProductController;
import com.agrocomercial.clientes.events.OrderCreatedEventListener;
import com.agrocomercial.clientes.models.Order;
import com.agrocomercial.clientes.utils.WindowUtils;

import javax.swing.table.DefaultTableModel;

import java.util.List;

import static com.agrocomercial.clientes.utils.WindowUtils.getTableModel;

/**
 *
 * @author Jesús Perea
 */
public class ListOrdersView extends javax.swing.JFrame implements OrderCreatedEventListener {

    private final transient AppContext localAppContext;
    private final transient OrderProductController orderProductController;

    /**
     * Creates new form ListOrdersView
     */
    public ListOrdersView(AppContext appContext, OrderProductController orderProductController) {
        initComponents();
        this.localAppContext = appContext;
        this.orderProductController = orderProductController;
        subscribeToOrderCreated();
        loadOrders();
    }

    private void subscribeToOrderCreated(){
        orderProductController.subscribeToOrderCreated(this);
    }

    private void loadOrders(){
        DefaultTableModel tableModel = getTableModel(ordersTable);
        List<Order> orders = orderProductController.getOrders();

        orders.forEach(order -> tableModel.addRow(
                new Object[]{order.getOrderNumber(), order.getSubtotal()}
        ));

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ordersTable = new javax.swing.JTable();
        createOrderButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ordersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero pedido", "subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ordersTable);
        if (ordersTable.getColumnModel().getColumnCount() > 0) {
            ordersTable.getColumnModel().getColumn(0).setResizable(false);
            ordersTable.getColumnModel().getColumn(1).setResizable(false);
        }

        createOrderButton.setText("Crear pedido");
        createOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createOrderButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(createOrderButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {
        WindowUtils.closeAndShowPanel(this, localAppContext.getCreateOrderView());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createOrderButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ordersTable;

    @Override
    public void onOrderCreated(Order order) {
        DefaultTableModel ordersTableModel = getTableModel(ordersTable);
        ordersTableModel.addRow(new Object[]{order.getOrderNumber(), order.getSubtotal()});
    }
    // End of variables declaration//GEN-END:variables
}
