/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.agrocomercial.clientes.views;

import com.agrocomercial.clientes.context.AppContext;
import com.agrocomercial.clientes.models.Customer;
import com.agrocomercial.clientes.models.User;
import com.agrocomercial.clientes.services.CustomerService;
import com.agrocomercial.clientes.services.UserService;
import com.agrocomercial.clientes.utils.WindowUtils;

import javax.swing.*;

/**
 *
 * @author Jesús Perea
 */
public class MainMenuView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainMenuView.class.getName());
    private final transient AppContext localAppContext;
    private final transient CustomerService customerService;
    private final transient UserService userService;

    /**
     * Creates new form MainMenuFrame
     */
    public MainMenuView(AppContext localAppContext, CustomerService customerService, UserService userService) {
        initComponents();
        this.localAppContext = localAppContext;
        this.customerService = customerService;
        this.userService = userService;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        customerRedirection = new javax.swing.JButton();
        ordersRedirection = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customerRedirection.setText("clientes");
        customerRedirection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerRedirectionActionPerformed(evt);
            }
        });

        ordersRedirection.setText("ordenes");
        ordersRedirection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersRedirectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(customerRedirection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ordersRedirection)
                .addGap(0, 240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerRedirection)
                    .addComponent(ordersRedirection))
                .addGap(0, 277, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerRedirectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerRedirectionActionPerformed
        validateRedirectToCustomerViews(localAppContext.getCustomerView());
    }//GEN-LAST:event_customerRedirectionActionPerformed

    private void ordersRedirectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersRedirectionActionPerformed
        validateRedirectToCustomerViews(localAppContext.getOrderView());
    }//GEN-LAST:event_ordersRedirectionActionPerformed

    private void validateRedirectToCustomerViews(JFrame view){
        Customer customer = customerService.findByUserId(
                userService.getLoggedUser().getId()
        );

        if(customer == null){
            JOptionPane.showMessageDialog(null, "El usuario no tiene acceso a esta vista");
            return;
        }

        WindowUtils.closeAndShowPanel(this, view);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerRedirection;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton ordersRedirection;
    // End of variables declaration//GEN-END:variables
}
